name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    if: GITHUB_ACTOR == 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_ACTOR}
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MYTOKEN }}